import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";

const LIB = join(import.meta.dirname, "..", "library");

const concepts = [
  // ── 01_elementary_math (15) ──
  { cat: "01_elementary_math", id: "addition", kr: "덧셈", en: "Addition", diff: "Elementary", conn: ["subtraction"], formula: "$$a + b = c$$", desc_kr: "두 수를 합하는 가장 기본적인 연산입니다.", desc_en: "The most fundamental operation of combining two numbers.", params: { numberA: { d: 5, min: 0, max: 20, step: 1, kr: "숫자 A", en: "Number A" }, numberB: { d: 3, min: 0, max: 20, step: 1, kr: "숫자 B", en: "Number B" }, showBlocks: { d: true, kr: "블록 보기", en: "Show Blocks" } }, real: ["장보기에서 가격 합산", "점수 합계 계산", "시간 더하기"] },
  { cat: "01_elementary_math", id: "subtraction", kr: "뺄셈", en: "Subtraction", diff: "Elementary", conn: ["addition"], formula: "$$a - b = c$$", desc_kr: "큰 수에서 작은 수를 빼는 연산입니다.", desc_en: "Taking one number away from another.", params: { numberA: { d: 10, min: 0, max: 20, step: 1, kr: "숫자 A", en: "Number A" }, numberB: { d: 4, min: 0, max: 20, step: 1, kr: "숫자 B", en: "Number B" }, showBlocks: { d: true, kr: "블록 보기", en: "Show Blocks" } }, real: ["거스름돈 계산", "남은 시간 계산", "온도 차이"] },
  { cat: "01_elementary_math", id: "multiplication", kr: "곱셈", en: "Multiplication", diff: "Elementary", conn: ["addition", "division"], formula: "$$a \\times b = c$$", desc_kr: "같은 수를 여러 번 더하는 것을 간단하게 표현한 연산입니다.", desc_en: "A shortcut for repeated addition.", params: { numberA: { d: 4, min: 1, max: 12, step: 1, kr: "숫자 A", en: "Number A" }, numberB: { d: 3, min: 1, max: 12, step: 1, kr: "숫자 B", en: "Number B" }, showGrid: { d: true, kr: "격자 보기", en: "Show Grid" } }, real: ["배열 계산", "넓이 구하기", "총 개수 세기"] },
  { cat: "01_elementary_math", id: "division", kr: "나눗셈", en: "Division", diff: "Elementary", conn: ["multiplication"], formula: "$$a \\div b = q \\cdots r$$", desc_kr: "하나의 수를 똑같이 나누는 연산입니다.", desc_en: "Splitting a number into equal parts.", params: { dividend: { d: 12, min: 1, max: 50, step: 1, kr: "피제수", en: "Dividend" }, divisor: { d: 4, min: 1, max: 12, step: 1, kr: "제수", en: "Divisor" }, showParts: { d: true, kr: "나눔 보기", en: "Show Parts" } }, real: ["피자 나누기", "용돈 분배", "시간 배분"] },
  { cat: "01_elementary_math", id: "fractions", kr: "분수", en: "Fractions", diff: "Elementary", conn: ["decimals", "division"], formula: "$$\\frac{a}{b}$$", desc_kr: "전체를 똑같이 나눈 것 중 일부를 나타내는 수입니다.", desc_en: "A number that represents a part of a whole.", params: { numerator: { d: 3, min: 1, max: 12, step: 1, kr: "분자", en: "Numerator" }, denominator: { d: 4, min: 2, max: 12, step: 1, kr: "분모", en: "Denominator" }, showPie: { d: true, kr: "원 그래프", en: "Pie Chart" } }, real: ["케이크 나누기", "시간의 분수 표현", "할인율 이해"] },
  { cat: "01_elementary_math", id: "decimals", kr: "소수", en: "Decimals", diff: "Elementary", conn: ["fractions"], formula: "$$0.1 = \\frac{1}{10}$$", desc_kr: "1보다 작은 수를 소수점을 사용하여 나타내는 방법입니다.", desc_en: "Numbers with a decimal point representing parts smaller than one.", params: { value: { d: 0.5, min: 0, max: 2, step: 0.1, kr: "값", en: "Value" }, showBar: { d: true, kr: "막대 보기", en: "Show Bar" } }, real: ["돈 계산 (원 단위)", "키와 몸무게 측정", "소수점 이하 온도"] },
  { cat: "01_elementary_math", id: "number-line", kr: "수직선", en: "Number Line", diff: "Elementary", conn: ["addition", "subtraction"], formula: "$$\\leftarrow \\cdots -2, -1, 0, 1, 2 \\cdots \\rightarrow$$", desc_kr: "수를 직선 위에 순서대로 나타낸 것입니다.", desc_en: "A visual representation of numbers on a straight line.", params: { position: { d: 3, min: -10, max: 10, step: 1, kr: "위치", en: "Position" }, rangeSize: { d: 10, min: 5, max: 20, step: 1, kr: "범위", en: "Range" }, showArrow: { d: true, kr: "이동 화살표", en: "Show Arrow" } }, real: ["온도계", "엘리베이터 층수", "타임라인"] },
  { cat: "01_elementary_math", id: "shapes-2d", kr: "평면도형", en: "2D Shapes", diff: "Elementary", conn: ["area-rectangle", "perimeter"], formula: "", desc_kr: "삼각형, 사각형, 원 등 평면 위에 그릴 수 있는 도형입니다.", desc_en: "Flat shapes like triangles, rectangles, and circles.", params: { sides: { d: 4, min: 3, max: 8, step: 1, kr: "변의 수", en: "Sides" }, size: { d: 3, min: 1, max: 6, step: 0.5, kr: "크기", en: "Size" }, showName: { d: true, kr: "이름 표시", en: "Show Name" } }, real: ["건물 바닥 모양", "표지판 모양", "타일 패턴"] },
  { cat: "01_elementary_math", id: "symmetry", kr: "대칭", en: "Symmetry", diff: "Elementary", conn: ["shapes-2d"], formula: "", desc_kr: "어떤 선을 중심으로 양쪽이 똑같은 모양인 것을 대칭이라 합니다.", desc_en: "When both sides of a shape are mirror images of each other.", params: { shape: { d: 4, min: 3, max: 8, step: 1, kr: "도형", en: "Shape" }, showAxis: { d: true, kr: "대칭축 보기", en: "Show Axis" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["나비 날개", "사람 얼굴", "건물 설계"] },
  { cat: "01_elementary_math", id: "area-rectangle", kr: "직사각형 넓이", en: "Rectangle Area", diff: "Elementary", conn: ["multiplication", "perimeter"], formula: "$$S = a \\times b$$", desc_kr: "직사각형의 넓이는 가로 곱하기 세로로 구합니다.", desc_en: "The area of a rectangle is width times height.", params: { width: { d: 5, min: 1, max: 10, step: 0.5, kr: "가로", en: "Width" }, height: { d: 3, min: 1, max: 10, step: 0.5, kr: "세로", en: "Height" }, showGrid: { d: true, kr: "격자 보기", en: "Show Grid" } }, real: ["방 크기 계산", "벽지 필요량", "농지 면적"] },
  { cat: "01_elementary_math", id: "perimeter", kr: "둘레", en: "Perimeter", diff: "Elementary", conn: ["addition", "area-rectangle"], formula: "$$P = 2(a + b)$$", desc_kr: "도형의 바깥쪽 테두리 길이를 둘레라고 합니다.", desc_en: "The total length of the boundary of a shape.", params: { width: { d: 5, min: 1, max: 10, step: 0.5, kr: "가로", en: "Width" }, height: { d: 3, min: 1, max: 10, step: 0.5, kr: "세로", en: "Height" }, showMeasure: { d: true, kr: "측정선 보기", en: "Show Measurement" } }, real: ["울타리 길이", "액자 테두리", "운동장 트랙"] },
  { cat: "01_elementary_math", id: "angles", kr: "각도", en: "Angles", diff: "Elementary", conn: ["shapes-2d"], formula: "$$0° \\leq \\theta \\leq 360°$$", desc_kr: "두 직선이 만나서 이루는 벌어진 정도를 각도라고 합니다.", desc_en: "The amount of turn between two lines meeting at a point.", params: { angle: { d: 90, min: 0, max: 360, step: 5, kr: "각도", en: "Angle" }, showProtractor: { d: true, kr: "각도기 보기", en: "Show Protractor" } }, real: ["시계 바늘 각도", "문 열림 각도", "경사로 기울기"] },
  { cat: "01_elementary_math", id: "patterns", kr: "규칙 찾기", en: "Patterns", diff: "Elementary", conn: ["sequences-series"], formula: "", desc_kr: "수나 도형이 일정한 규칙에 따라 반복되는 것을 찾는 활동입니다.", desc_en: "Finding rules in sequences of numbers or shapes.", params: { start: { d: 2, min: 1, max: 10, step: 1, kr: "시작 수", en: "Start" }, step: { d: 3, min: 1, max: 10, step: 1, kr: "규칙 (더하기)", en: "Rule (add)" }, showNext: { d: true, kr: "다음 수 보기", en: "Show Next" } }, real: ["음악의 리듬", "타일 무늬", "달력의 요일"] },
  { cat: "01_elementary_math", id: "bar-graph", kr: "막대그래프", en: "Bar Graph", diff: "Elementary", conn: ["statistics-mean"], formula: "", desc_kr: "자료의 크기를 막대의 길이로 나타낸 그래프입니다.", desc_en: "A chart that uses bars to show data values.", params: { value1: { d: 5, min: 0, max: 10, step: 1, kr: "값 A", en: "Value A" }, value2: { d: 8, min: 0, max: 10, step: 1, kr: "값 B", en: "Value B" }, value3: { d: 3, min: 0, max: 10, step: 1, kr: "값 C", en: "Value C" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["학급 선호도 조사", "월별 기온 비교", "판매량 비교"] },
  { cat: "01_elementary_math", id: "clock-time", kr: "시계와 시간", en: "Clock & Time", diff: "Elementary", conn: ["angles"], formula: "", desc_kr: "시계의 바늘이 움직이면서 시간을 나타내는 원리를 배웁니다.", desc_en: "Understanding how clock hands show time.", params: { hours: { d: 3, min: 0, max: 12, step: 1, kr: "시", en: "Hours" }, minutes: { d: 30, min: 0, max: 59, step: 5, kr: "분", en: "Minutes" }, showAngle: { d: true, kr: "각도 표시", en: "Show Angle" } }, real: ["일상 시간 관리", "알람 설정", "시차 계산"] },

  // ── 02_middle_math (17) ──
  { cat: "02_middle_math", id: "integers", kr: "정수", en: "Integers", diff: "Middle-1", conn: ["number-line", "rational-numbers"], formula: "$$\\mathbb{Z} = \\{\\ldots, -2, -1, 0, 1, 2, \\ldots\\}$$", desc_kr: "양의 정수, 0, 음의 정수를 모두 포함하는 수의 집합입니다.", desc_en: "The set of whole numbers including negatives, zero, and positives.", params: { valueA: { d: 5, min: -10, max: 10, step: 1, kr: "정수 A", en: "Integer A" }, valueB: { d: -3, min: -10, max: 10, step: 1, kr: "정수 B", en: "Integer B" }, showLine: { d: true, kr: "수직선 보기", en: "Show Number Line" } }, real: ["영하 온도", "해발 고도", "은행 잔고"] },
  { cat: "02_middle_math", id: "rational-numbers", kr: "유리수", en: "Rational Numbers", diff: "Middle-1", conn: ["integers", "fractions"], formula: "$$\\frac{p}{q}, \\; q \\neq 0$$", desc_kr: "두 정수의 비로 나타낼 수 있는 수를 유리수라 합니다.", desc_en: "Numbers that can be expressed as a fraction of two integers.", params: { numerator: { d: 3, min: -10, max: 10, step: 1, kr: "분자", en: "Numerator" }, denominator: { d: 4, min: 1, max: 10, step: 1, kr: "분모", en: "Denominator" }, showDecimal: { d: true, kr: "소수 변환", en: "Show Decimal" } }, real: ["비율 계산", "할인율", "레시피 비율"] },
  { cat: "02_middle_math", id: "linear-equation", kr: "일차방정식", en: "Linear Equation", diff: "Middle-1", conn: ["linear-function"], formula: "$$ax + b = 0$$", desc_kr: "미지수의 최고 차수가 1인 방정식입니다.", desc_en: "An equation where the highest power of the variable is 1.", params: { a: { d: 2, min: -5, max: 5, step: 0.5, kr: "계수 a", en: "Coefficient a" }, b: { d: -4, min: -10, max: 10, step: 0.5, kr: "상수 b", en: "Constant b" }, showSolution: { d: true, kr: "해 표시", en: "Show Solution" } }, real: ["가격 계산", "속도·시간·거리 관계", "나이 문제"] },
  { cat: "02_middle_math", id: "linear-function", kr: "일차함수", en: "Linear Function", diff: "Middle-2", conn: ["linear-equation", "coordinate-plane"], formula: "$$y = ax + b$$", desc_kr: "그래프가 직선인 함수로, 기울기와 y절편으로 결정됩니다.", desc_en: "A function whose graph is a straight line.", params: { slope: { d: 2, min: -5, max: 5, step: 0.5, kr: "기울기", en: "Slope" }, intercept: { d: 1, min: -5, max: 5, step: 0.5, kr: "y절편", en: "y-intercept" }, showGrid: { d: true, kr: "격자 보기", en: "Show Grid" } }, real: ["택시 요금 구조", "온도 변환", "급여 계산"] },
  { cat: "02_middle_math", id: "similar-triangles", kr: "닮음", en: "Similar Triangles", diff: "Middle-2", conn: ["pythagorean-theorem", "proportion"], formula: "$$\\frac{a}{a'} = \\frac{b}{b'} = \\frac{c}{c'}$$", desc_kr: "모양은 같고 크기만 다른 도형의 관계를 닮음이라 합니다.", desc_en: "Figures that have the same shape but may differ in size.", params: { scale: { d: 2, min: 0.5, max: 4, step: 0.1, kr: "축척 비", en: "Scale Ratio" }, sideA: { d: 3, min: 1, max: 8, step: 0.5, kr: "변 a", en: "Side a" }, showRatio: { d: true, kr: "비율 표시", en: "Show Ratio" } }, real: ["지도 축척", "사진 확대/축소", "그림자 길이 측정"] },
  { cat: "02_middle_math", id: "circle-properties", kr: "원의 성질", en: "Circle Properties", diff: "Middle-2", conn: ["unit-circle", "angles"], formula: "$$C = 2\\pi r, \\; A = \\pi r^2$$", desc_kr: "원의 둘레와 넓이, 중심각과 호의 관계를 다룹니다.", desc_en: "Properties of circles including circumference, area, and arcs.", params: { radius: { d: 3, min: 0.5, max: 6, step: 0.5, kr: "반지름", en: "Radius" }, centralAngle: { d: 90, min: 0, max: 360, step: 5, kr: "중심각", en: "Central Angle" }, showArea: { d: true, kr: "넓이 표시", en: "Show Area" } }, real: ["바퀴의 둘레", "피자 면적", "원형 화단"] },
  { cat: "02_middle_math", id: "probability-basic", kr: "확률 기초", en: "Basic Probability", diff: "Middle-2", conn: ["statistics-mean"], formula: "$$P(A) = \\frac{n(A)}{n(S)}$$", desc_kr: "어떤 사건이 일어날 가능성을 수로 나타낸 것입니다.", desc_en: "The numerical measure of the likelihood of an event occurring.", params: { favorable: { d: 3, min: 1, max: 12, step: 1, kr: "유리한 경우", en: "Favorable" }, total: { d: 6, min: 2, max: 12, step: 1, kr: "전체 경우", en: "Total" }, showDice: { d: true, kr: "주사위 보기", en: "Show Dice" } }, real: ["동전 던지기", "주사위 게임", "날씨 예보 확률"] },
  { cat: "02_middle_math", id: "quadratic-equation", kr: "이차방정식", en: "Quadratic Equation", diff: "Middle-3", conn: ["quadratic-function", "square-root"], formula: "$$ax^2 + bx + c = 0$$", desc_kr: "미지수의 최고 차수가 2인 방정식으로, 근의 공식으로 풀 수 있습니다.", desc_en: "An equation with the variable raised to the second power.", params: { a: { d: 1, min: -3, max: 3, step: 0.5, kr: "계수 a", en: "Coefficient a" }, b: { d: -3, min: -6, max: 6, step: 0.5, kr: "계수 b", en: "Coefficient b" }, c: { d: 2, min: -6, max: 6, step: 0.5, kr: "상수 c", en: "Constant c" }, showRoots: { d: true, kr: "근 표시", en: "Show Roots" } }, real: ["포물선 궤적", "면적 최적화", "이윤 최대화"] },
  { cat: "02_middle_math", id: "inequality", kr: "부등식", en: "Inequality", diff: "Middle-2", conn: ["linear-equation"], formula: "$$ax + b > 0$$", desc_kr: "두 수 또는 식의 크기를 비교하는 관계식입니다.", desc_en: "A mathematical statement comparing two values using inequality signs.", params: { a: { d: 2, min: -5, max: 5, step: 0.5, kr: "계수 a", en: "Coefficient a" }, b: { d: -3, min: -10, max: 10, step: 0.5, kr: "상수 b", en: "Constant b" }, showRegion: { d: true, kr: "영역 표시", en: "Show Region" } }, real: ["예산 제한", "속도 제한", "최소 점수 조건"] },
  { cat: "02_middle_math", id: "coordinate-plane", kr: "좌표평면", en: "Coordinate Plane", diff: "Middle-1", conn: ["linear-function", "number-line"], formula: "$$P(x, y)$$", desc_kr: "x축과 y축이 만나는 평면 위에 점의 위치를 나타내는 체계입니다.", desc_en: "A two-dimensional surface where points are located using x and y coordinates.", params: { pointX: { d: 3, min: -5, max: 5, step: 0.5, kr: "x 좌표", en: "x coordinate" }, pointY: { d: 4, min: -5, max: 5, step: 0.5, kr: "y 좌표", en: "y coordinate" }, showQuadrants: { d: true, kr: "사분면 표시", en: "Show Quadrants" } }, real: ["지도 좌표", "게임 캐릭터 위치", "GPS 위치"] },
  { cat: "02_middle_math", id: "statistics-mean", kr: "평균과 분산", en: "Mean & Variance", diff: "Middle-3", conn: ["bar-graph", "probability-basic"], formula: "$$\\bar{x} = \\frac{1}{n}\\sum_{i=1}^{n}x_i$$", desc_kr: "자료의 중심 경향과 흩어진 정도를 수치로 나타냅니다.", desc_en: "Measures of central tendency and spread of data.", params: { value1: { d: 5, min: 0, max: 10, step: 1, kr: "자료 1", en: "Data 1" }, value2: { d: 7, min: 0, max: 10, step: 1, kr: "자료 2", en: "Data 2" }, value3: { d: 3, min: 0, max: 10, step: 1, kr: "자료 3", en: "Data 3" }, value4: { d: 9, min: 0, max: 10, step: 1, kr: "자료 4", en: "Data 4" } }, real: ["성적 평균", "일기예보 평균 기온", "품질 관리"] },
  { cat: "02_middle_math", id: "exponents", kr: "거듭제곱", en: "Exponents", diff: "Middle-1", conn: ["multiplication", "square-root"], formula: "$$a^n = \\underbrace{a \\times a \\times \\cdots \\times a}_{n}$$", desc_kr: "같은 수를 여러 번 곱하는 것을 간단히 나타낸 것입니다.", desc_en: "Repeated multiplication of the same number.", params: { base: { d: 2, min: 1, max: 5, step: 1, kr: "밑", en: "Base" }, exponent: { d: 3, min: 1, max: 8, step: 1, kr: "지수", en: "Exponent" }, showSteps: { d: true, kr: "과정 표시", en: "Show Steps" } }, real: ["세포 분열", "복리 이자", "데이터 단위 (KB, MB, GB)"] },
  { cat: "02_middle_math", id: "square-root", kr: "제곱근", en: "Square Root", diff: "Middle-3", conn: ["exponents", "pythagorean-theorem"], formula: "$$\\sqrt{a} = b \\;\\Leftrightarrow\\; b^2 = a$$", desc_kr: "제곱하여 a가 되는 수를 a의 제곱근이라 합니다.", desc_en: "A number that when multiplied by itself gives the original number.", params: { value: { d: 9, min: 1, max: 25, step: 1, kr: "값", en: "Value" }, showSquare: { d: true, kr: "정사각형 보기", en: "Show Square" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["대각선 길이 계산", "면적에서 한 변 구하기", "피타고라스 정리 활용"] },
  { cat: "02_middle_math", id: "proportion", kr: "비례", en: "Proportion", diff: "Middle-1", conn: ["linear-function", "similar-triangles"], formula: "$$y = kx$$", desc_kr: "두 양이 일정한 비율을 유지하며 변하는 관계입니다.", desc_en: "A relationship where two quantities change at the same rate.", params: { ratio: { d: 2, min: 0.5, max: 5, step: 0.5, kr: "비율 k", en: "Ratio k" }, maxX: { d: 5, min: 1, max: 10, step: 1, kr: "x 범위", en: "x Range" }, showTable: { d: true, kr: "표 보기", en: "Show Table" } }, real: ["레시피 비율", "지도 축척", "환율 계산"] },
  { cat: "02_middle_math", id: "factoring", kr: "인수분해", en: "Factoring", diff: "Middle-3", conn: ["quadratic-equation", "exponents"], formula: "$$x^2 + (a+b)x + ab = (x+a)(x+b)$$", desc_kr: "다항식을 두 개 이상의 인수의 곱으로 나타내는 것입니다.", desc_en: "Expressing a polynomial as a product of its factors.", params: { a: { d: 2, min: -5, max: 5, step: 1, kr: "인수 a", en: "Factor a" }, b: { d: 3, min: -5, max: 5, step: 1, kr: "인수 b", en: "Factor b" }, showExpanded: { d: true, kr: "전개 표시", en: "Show Expanded" } }, real: ["넓이 분해", "암호학 기초", "최적화 문제"] },
  { cat: "02_middle_math", id: "sets", kr: "집합", en: "Sets", diff: "Middle-3", conn: ["probability-basic"], formula: "$$A \\cup B, \\; A \\cap B$$", desc_kr: "공통된 성질을 가진 것들의 모임을 집합이라 합니다.", desc_en: "A collection of distinct objects grouped together.", params: { sizeA: { d: 5, min: 1, max: 10, step: 1, kr: "집합 A 크기", en: "Set A size" }, sizeB: { d: 4, min: 1, max: 10, step: 1, kr: "집합 B 크기", en: "Set B size" }, overlap: { d: 2, min: 0, max: 5, step: 1, kr: "교집합 크기", en: "Overlap" }, showVenn: { d: true, kr: "벤 다이어그램", en: "Venn Diagram" } }, real: ["데이터베이스 검색", "설문 조사 분석", "논리적 분류"] },

  // ── 03_middle_physics (12) ──
  { cat: "03_middle_physics", id: "speed-velocity", kr: "속력과 속도", en: "Speed & Velocity", diff: "Middle-1", conn: ["force-motion"], formula: "$$v = \\frac{d}{t}$$", desc_kr: "물체가 일정 시간 동안 이동한 거리의 비율입니다.", desc_en: "The rate at which an object covers distance over time.", params: { distance: { d: 100, min: 10, max: 500, step: 10, kr: "거리 (m)", en: "Distance (m)" }, time: { d: 10, min: 1, max: 30, step: 1, kr: "시간 (s)", en: "Time (s)" }, showPath: { d: true, kr: "경로 보기", en: "Show Path" } }, real: ["자동차 속도", "달리기 기록", "비행기 속도"] },
  { cat: "03_middle_physics", id: "force-motion", kr: "힘과 운동", en: "Force & Motion", diff: "Middle-2", conn: ["speed-velocity", "gravity", "newtons-laws"], formula: "$$F = ma$$", desc_kr: "물체에 힘이 작용하면 가속도가 생기며 운동 상태가 변합니다.", desc_en: "When a force acts on an object, it causes acceleration.", params: { mass: { d: 5, min: 1, max: 20, step: 1, kr: "질량 (kg)", en: "Mass (kg)" }, force: { d: 10, min: 1, max: 50, step: 1, kr: "힘 (N)", en: "Force (N)" }, showVector: { d: true, kr: "벡터 표시", en: "Show Vector" } }, real: ["자동차 가속", "엘리베이터 운동", "로켓 발사"] },
  { cat: "03_middle_physics", id: "gravity", kr: "중력", en: "Gravity", diff: "Middle-1", conn: ["force-motion", "projectile-motion"], formula: "$$F = mg, \\; g \\approx 9.8\\,m/s^2$$", desc_kr: "지구가 물체를 끌어당기는 힘입니다.", desc_en: "The force that pulls objects toward the center of the Earth.", params: { mass: { d: 1, min: 0.1, max: 10, step: 0.1, kr: "질량 (kg)", en: "Mass (kg)" }, height: { d: 10, min: 1, max: 50, step: 1, kr: "높이 (m)", en: "Height (m)" }, showFall: { d: true, kr: "낙하 보기", en: "Show Fall" } }, real: ["자유 낙하", "체중 측정", "행성별 중력 차이"] },
  { cat: "03_middle_physics", id: "light-reflection", kr: "빛의 반사", en: "Light Reflection", diff: "Middle-2", conn: ["light-refraction", "angles"], formula: "$$\\theta_i = \\theta_r$$", desc_kr: "빛이 거울 같은 면에 부딪혀 되돌아오는 현상입니다.", desc_en: "When light bounces off a surface at the same angle it hits.", params: { angle: { d: 45, min: 5, max: 85, step: 5, kr: "입사각 (°)", en: "Angle of Incidence (°)" }, showNormal: { d: true, kr: "법선 보기", en: "Show Normal" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["거울", "레이저 반사", "잠망경"] },
  { cat: "03_middle_physics", id: "light-refraction", kr: "빛의 굴절", en: "Light Refraction", diff: "Middle-2", conn: ["light-reflection"], formula: "$$n_1 \\sin\\theta_1 = n_2 \\sin\\theta_2$$", desc_kr: "빛이 다른 매질을 통과할 때 꺾이는 현상입니다.", desc_en: "The bending of light as it passes from one medium to another.", params: { angle: { d: 45, min: 5, max: 85, step: 5, kr: "입사각 (°)", en: "Angle (°)" }, n1: { d: 1, min: 1, max: 2.5, step: 0.1, kr: "굴절률 n₁", en: "Index n₁" }, n2: { d: 1.5, min: 1, max: 2.5, step: 0.1, kr: "굴절률 n₂", en: "Index n₂" } }, real: ["물속 물체가 휘어 보임", "렌즈", "무지개"] },
  { cat: "03_middle_physics", id: "waves-basic", kr: "파동 기초", en: "Basic Waves", diff: "Middle-2", conn: ["sine-wave", "wave-interference"], formula: "$$v = f\\lambda$$", desc_kr: "에너지가 매질을 통해 전달되는 현상입니다.", desc_en: "A disturbance that transfers energy through a medium.", params: { amplitude: { d: 1, min: 0.2, max: 3, step: 0.1, kr: "진폭", en: "Amplitude" }, frequency: { d: 2, min: 0.5, max: 5, step: 0.5, kr: "진동수", en: "Frequency" }, showWavelength: { d: true, kr: "파장 표시", en: "Show Wavelength" } }, real: ["음파", "지진파", "수면파"] },
  { cat: "03_middle_physics", id: "electric-circuit", kr: "전기 회로", en: "Electric Circuit", diff: "Middle-2", conn: ["ohms-law"], formula: "$$V = IR$$", desc_kr: "전류가 흐르는 도선과 전기 부품으로 이루어진 닫힌 경로입니다.", desc_en: "A closed path through which electric current flows.", params: { voltage: { d: 9, min: 1, max: 24, step: 1, kr: "전압 (V)", en: "Voltage (V)" }, resistance: { d: 3, min: 1, max: 10, step: 0.5, kr: "저항 (Ω)", en: "Resistance (Ω)" }, showCurrent: { d: true, kr: "전류 표시", en: "Show Current" } }, real: ["손전등", "가전제품 연결", "스마트폰 충전"] },
  { cat: "03_middle_physics", id: "density", kr: "밀도", en: "Density", diff: "Middle-1", conn: ["buoyancy"], formula: "$$\\rho = \\frac{m}{V}$$", desc_kr: "단위 부피당 물질의 질량입니다.", desc_en: "The amount of mass per unit volume of a substance.", params: { mass: { d: 10, min: 1, max: 50, step: 1, kr: "질량 (g)", en: "Mass (g)" }, volume: { d: 5, min: 1, max: 20, step: 1, kr: "부피 (cm³)", en: "Volume (cm³)" }, showCompare: { d: true, kr: "비교 보기", en: "Show Comparison" } }, real: ["물에 뜨는 물체", "금속 구분", "기름과 물의 층"] },
  { cat: "03_middle_physics", id: "energy-conservation", kr: "에너지 보존", en: "Energy Conservation", diff: "Middle-3", conn: ["work-energy", "gravity"], formula: "$$E_k + E_p = \\text{const}$$", desc_kr: "에너지는 형태가 바뀔 수 있지만 총량은 변하지 않습니다.", desc_en: "Energy cannot be created or destroyed, only transformed.", params: { height: { d: 10, min: 1, max: 20, step: 1, kr: "높이 (m)", en: "Height (m)" }, mass: { d: 2, min: 0.5, max: 5, step: 0.5, kr: "질량 (kg)", en: "Mass (kg)" }, showBars: { d: true, kr: "에너지 막대", en: "Energy Bars" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["롤러코스터", "공 던지기", "진자 시계"] },
  { cat: "03_middle_physics", id: "heat-transfer", kr: "열전달", en: "Heat Transfer", diff: "Middle-2", conn: ["thermodynamics"], formula: "$$Q = mc\\Delta T$$", desc_kr: "온도가 다른 두 물체 사이에서 에너지가 이동하는 현상입니다.", desc_en: "The movement of thermal energy from hot to cold objects.", params: { tempHot: { d: 80, min: 20, max: 100, step: 5, kr: "고온 (°C)", en: "Hot (°C)" }, tempCold: { d: 20, min: 0, max: 50, step: 5, kr: "저온 (°C)", en: "Cold (°C)" }, showFlow: { d: true, kr: "열 흐름 보기", en: "Show Heat Flow" } }, real: ["요리할 때 열전달", "핫팩과 쿨팩", "단열재의 원리"] },
  { cat: "03_middle_physics", id: "pressure", kr: "압력", en: "Pressure", diff: "Middle-2", conn: ["density", "buoyancy"], formula: "$$P = \\frac{F}{A}$$", desc_kr: "단위 면적에 가해지는 힘의 크기입니다.", desc_en: "The force applied per unit area.", params: { force: { d: 100, min: 10, max: 500, step: 10, kr: "힘 (N)", en: "Force (N)" }, area: { d: 10, min: 1, max: 50, step: 1, kr: "면적 (cm²)", en: "Area (cm²)" }, showArrows: { d: true, kr: "화살표 보기", en: "Show Arrows" } }, real: ["못과 압정", "스키와 설피", "자동차 타이어"] },
  { cat: "03_middle_physics", id: "buoyancy", kr: "부력", en: "Buoyancy", diff: "Middle-2", conn: ["density", "pressure"], formula: "$$F_b = \\rho_{fluid} \\cdot V \\cdot g$$", desc_kr: "유체 속의 물체가 위로 떠오르려는 힘입니다.", desc_en: "The upward force exerted on an object submerged in fluid.", params: { objectDensity: { d: 800, min: 100, max: 2000, step: 100, kr: "물체 밀도", en: "Object Density" }, fluidDensity: { d: 1000, min: 500, max: 1500, step: 100, kr: "유체 밀도", en: "Fluid Density" }, showForces: { d: true, kr: "힘 표시", en: "Show Forces" } }, real: ["배가 뜨는 원리", "잠수함", "열기구"] },

  // ── 04_high_math (18, sine-wave and unit-circle already exist) ──
  { cat: "04_high_math", id: "quadratic-function", kr: "이차함수", en: "Quadratic Function", diff: "High-1", conn: ["quadratic-equation", "linear-function"], formula: "$$y = ax^2 + bx + c$$", desc_kr: "그래프가 포물선인 함수로, 꼭짓점과 축을 기준으로 대칭입니다.", desc_en: "A function whose graph is a parabola.", params: { a: { d: 1, min: -3, max: 3, step: 0.25, kr: "계수 a", en: "Coeff a" }, b: { d: 0, min: -4, max: 4, step: 0.5, kr: "계수 b", en: "Coeff b" }, c: { d: 0, min: -4, max: 4, step: 0.5, kr: "상수 c", en: "Constant c" }, showVertex: { d: true, kr: "꼭짓점 표시", en: "Show Vertex" } }, real: ["포물선 운동", "다리 구조", "수익 최적화"] },
  { cat: "04_high_math", id: "trigonometric-functions", kr: "삼각함수", en: "Trigonometric Functions", diff: "High-1", conn: ["sine-wave", "unit-circle"], formula: "$$\\sin\\theta, \\; \\cos\\theta, \\; \\tan\\theta$$", desc_kr: "직각삼각형의 변의 비로 정의되는 함수들입니다.", desc_en: "Functions relating angles to ratios of triangle sides.", params: { angle: { d: 0.785, min: 0, max: 6.28, step: 0.05, kr: "각도 (rad)", en: "Angle (rad)" }, showAll: { d: true, kr: "sin/cos/tan 모두", en: "Show All" }, animate: { d: false, kr: "자동 회전", en: "Auto Rotate" } }, real: ["건축 각도 계산", "항해 방향", "음파 분석"] },
  { cat: "04_high_math", id: "logarithm", kr: "로그", en: "Logarithm", diff: "High-1", conn: ["exponential-function", "exponents"], formula: "$$\\log_a x = y \\;\\Leftrightarrow\\; a^y = x$$", desc_kr: "거듭제곱의 역연산으로, 지수를 구하는 연산입니다.", desc_en: "The inverse operation of exponentiation.", params: { base: { d: 2, min: 1.5, max: 10, step: 0.5, kr: "밑", en: "Base" }, maxX: { d: 16, min: 2, max: 50, step: 1, kr: "x 범위", en: "x Range" }, showInverse: { d: true, kr: "역함수 보기", en: "Show Inverse" } }, real: ["지진 규모 (리히터)", "소리 크기 (데시벨)", "pH 척도"] },
  { cat: "04_high_math", id: "exponential-function", kr: "지수함수", en: "Exponential Function", diff: "High-1", conn: ["logarithm", "exponents"], formula: "$$y = a^x$$", desc_kr: "밑이 일정하고 지수가 변수인 함수로, 급격한 증가/감소를 나타냅니다.", desc_en: "A function where the variable is in the exponent, showing rapid growth or decay.", params: { base: { d: 2, min: 0.2, max: 4, step: 0.1, kr: "밑 a", en: "Base a" }, showAsymptote: { d: true, kr: "점근선 보기", en: "Show Asymptote" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["인구 증가", "방사성 붕괴", "복리 이자 성장"] },
  { cat: "04_high_math", id: "limits", kr: "극한", en: "Limits", diff: "High-2", conn: ["derivatives", "sequences-series"], formula: "$$\\lim_{x \\to a} f(x) = L$$", desc_kr: "x가 특정 값에 한없이 가까워질 때 함수값이 다가가는 값입니다.", desc_en: "The value a function approaches as the input approaches a given value.", params: { approach: { d: 2, min: -3, max: 3, step: 0.5, kr: "접근값", en: "Approach" }, showTrace: { d: true, kr: "추적 보기", en: "Show Trace" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["속도의 순간값", "인구 포화 모델", "무한 소수의 극한"] },
  { cat: "04_high_math", id: "derivatives", kr: "미분", en: "Derivatives", diff: "High-2", conn: ["limits", "integrals"], formula: "$$f'(x) = \\lim_{h \\to 0} \\frac{f(x+h) - f(x)}{h}$$", desc_kr: "함수의 순간 변화율을 구하는 연산입니다.", desc_en: "The instantaneous rate of change of a function.", params: { power: { d: 2, min: 1, max: 4, step: 1, kr: "차수 n", en: "Power n" }, xPos: { d: 1, min: -3, max: 3, step: 0.1, kr: "x 위치", en: "x Position" }, showTangent: { d: true, kr: "접선 보기", en: "Show Tangent" } }, real: ["속도 = 위치의 미분", "가속도 = 속도의 미분", "최대/최소값 구하기"] },
  { cat: "04_high_math", id: "integrals", kr: "적분", en: "Integrals", diff: "High-2", conn: ["derivatives", "area-rectangle"], formula: "$$\\int_a^b f(x)\\,dx$$", desc_kr: "함수의 그래프와 x축 사이의 넓이를 구하는 연산입니다.", desc_en: "Finding the area under a curve between two points.", params: { power: { d: 2, min: 1, max: 3, step: 1, kr: "차수 n", en: "Power n" }, rangeA: { d: 0, min: -3, max: 3, step: 0.5, kr: "하한 a", en: "Lower a" }, rangeB: { d: 2, min: -3, max: 3, step: 0.5, kr: "상한 b", en: "Upper b" }, showRiemann: { d: true, kr: "리만 합 보기", en: "Show Riemann Sum" } }, real: ["면적 계산", "이동 거리 계산", "부피 계산"] },
  { cat: "04_high_math", id: "sequences-series", kr: "수열", en: "Sequences & Series", diff: "High-1", conn: ["patterns", "limits"], formula: "$$a_n = a_1 + (n-1)d$$", desc_kr: "일정한 규칙에 따라 나열된 수의 열입니다.", desc_en: "An ordered list of numbers following a specific pattern.", params: { first: { d: 1, min: 0, max: 10, step: 1, kr: "첫째항", en: "First term" }, diff: { d: 3, min: -5, max: 5, step: 1, kr: "공차", en: "Common diff" }, terms: { d: 8, min: 3, max: 15, step: 1, kr: "항의 수", en: "Terms" }, showSum: { d: true, kr: "합 표시", en: "Show Sum" } }, real: ["급여 인상 패턴", "좌석 배열", "적금 이자"] },
  { cat: "04_high_math", id: "vectors", kr: "벡터", en: "Vectors", diff: "High-1", conn: ["coordinate-plane", "matrices"], formula: "$$\\vec{v} = (v_x, v_y)$$", desc_kr: "크기와 방향을 모두 가진 양으로, 화살표로 나타냅니다.", desc_en: "A quantity with both magnitude and direction.", params: { vx: { d: 3, min: -5, max: 5, step: 0.5, kr: "x 성분", en: "x component" }, vy: { d: 4, min: -5, max: 5, step: 0.5, kr: "y 성분", en: "y component" }, showMagnitude: { d: true, kr: "크기 표시", en: "Show Magnitude" }, showAngle: { d: true, kr: "각도 표시", en: "Show Angle" } }, real: ["바람 방향과 세기", "물체 운동 방향", "항공기 항로"] },
  { cat: "04_high_math", id: "matrices", kr: "행렬", en: "Matrices", diff: "High-2", conn: ["vectors", "linear-equation"], formula: "$$A = \\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}$$", desc_kr: "수를 직사각형 형태로 배열한 것으로, 연립방정식과 변환에 쓰입니다.", desc_en: "Rectangular arrays of numbers used for transformations and solving systems.", params: { a: { d: 2, min: -5, max: 5, step: 1, kr: "a", en: "a" }, b: { d: 1, min: -5, max: 5, step: 1, kr: "b", en: "b" }, c: { d: 0, min: -5, max: 5, step: 1, kr: "c", en: "c" }, d_: { d: 2, min: -5, max: 5, step: 1, kr: "d", en: "d" }, showTransform: { d: true, kr: "변환 보기", en: "Show Transform" } }, real: ["3D 그래픽 변환", "암호 해독", "경제 모델"] },
  { cat: "04_high_math", id: "complex-numbers", kr: "복소수", en: "Complex Numbers", diff: "High-2", conn: ["quadratic-equation", "vectors"], formula: "$$z = a + bi, \\; i^2 = -1$$", desc_kr: "실수와 허수의 합으로 이루어진 수입니다.", desc_en: "Numbers with a real part and an imaginary part.", params: { real: { d: 3, min: -5, max: 5, step: 0.5, kr: "실수부 a", en: "Real part a" }, imaginary: { d: 2, min: -5, max: 5, step: 0.5, kr: "허수부 b", en: "Imaginary b" }, showPolar: { d: true, kr: "극형식 보기", en: "Show Polar" } }, real: ["전자공학 교류 회로", "양자역학", "신호 처리"] },
  { cat: "04_high_math", id: "permutation-combination", kr: "순열과 조합", en: "Permutation & Combination", diff: "High-1", conn: ["probability-basic", "factoring"], formula: "$$_nP_r = \\frac{n!}{(n-r)!}, \\; _nC_r = \\frac{n!}{r!(n-r)!}$$", desc_kr: "서로 다른 n개에서 r개를 뽑는 경우의 수입니다.", desc_en: "Counting arrangements and selections from a set.", params: { n: { d: 5, min: 2, max: 10, step: 1, kr: "전체 n", en: "Total n" }, r: { d: 3, min: 1, max: 8, step: 1, kr: "선택 r", en: "Choose r" }, showPermutation: { d: true, kr: "순열 보기", en: "Show Permutation" } }, real: ["비밀번호 가짓수", "로또 당첨 확률", "대진표 편성"] },
  { cat: "04_high_math", id: "conic-sections", kr: "이차곡선", en: "Conic Sections", diff: "High-3", conn: ["quadratic-function", "circle-properties"], formula: "$$\\frac{x^2}{a^2} + \\frac{y^2}{b^2} = 1$$", desc_kr: "원뿔을 잘랐을 때 나타나는 곡선 — 원, 타원, 포물선, 쌍곡선입니다.", desc_en: "Curves formed by intersecting a cone: circle, ellipse, parabola, hyperbola.", params: { a: { d: 3, min: 1, max: 6, step: 0.5, kr: "반축 a", en: "Semi-axis a" }, b: { d: 2, min: 1, max: 6, step: 0.5, kr: "반축 b", en: "Semi-axis b" }, showFoci: { d: true, kr: "초점 표시", en: "Show Foci" } }, real: ["행성 궤도", "위성 안테나", "아치 다리 설계"] },
  { cat: "04_high_math", id: "polynomial", kr: "다항함수", en: "Polynomial Function", diff: "High-1", conn: ["quadratic-function", "derivatives"], formula: "$$f(x) = a_nx^n + a_{n-1}x^{n-1} + \\cdots + a_0$$", desc_kr: "여러 항의 합으로 이루어진 함수입니다.", desc_en: "A function expressed as the sum of terms with variable powers.", params: { degree: { d: 3, min: 1, max: 5, step: 1, kr: "차수", en: "Degree" }, a1: { d: 1, min: -3, max: 3, step: 0.5, kr: "최고차 계수", en: "Leading coeff" }, showRoots: { d: true, kr: "근 표시", en: "Show Roots" } }, real: ["물리 궤적 모델링", "경제 비용 함수", "곡선 피팅"] },
  { cat: "04_high_math", id: "arithmetic-series", kr: "등차급수", en: "Arithmetic Series", diff: "High-1", conn: ["sequences-series"], formula: "$$S_n = \\frac{n(a_1 + a_n)}{2}$$", desc_kr: "등차수열의 항들을 모두 더한 합입니다.", desc_en: "The sum of terms in an arithmetic sequence.", params: { first: { d: 1, min: 0, max: 10, step: 1, kr: "첫째항", en: "First term" }, diff: { d: 2, min: 1, max: 5, step: 1, kr: "공차", en: "Common diff" }, n: { d: 10, min: 2, max: 20, step: 1, kr: "항 수", en: "Terms" }, showStack: { d: true, kr: "쌓기 보기", en: "Show Stack" } }, real: ["가우스의 합 공식", "계단식 좌석", "적금 총액"] },
  { cat: "04_high_math", id: "geometric-series", kr: "등비급수", en: "Geometric Series", diff: "High-1", conn: ["sequences-series", "exponential-function"], formula: "$$S_n = a_1 \\cdot \\frac{1 - r^n}{1 - r}$$", desc_kr: "등비수열의 항들을 모두 더한 합입니다.", desc_en: "The sum of terms in a geometric sequence.", params: { first: { d: 1, min: 0.5, max: 5, step: 0.5, kr: "첫째항", en: "First term" }, ratio: { d: 0.5, min: 0.1, max: 2, step: 0.1, kr: "공비", en: "Common ratio" }, n: { d: 8, min: 2, max: 15, step: 1, kr: "항 수", en: "Terms" }, showBars: { d: true, kr: "막대 보기", en: "Show Bars" } }, real: ["반감기 계산", "프랙탈 도형", "무한등비급수의 합"] },
  { cat: "04_high_math", id: "binomial-theorem", kr: "이항정리", en: "Binomial Theorem", diff: "High-2", conn: ["permutation-combination", "exponents"], formula: "$$(a+b)^n = \\sum_{k=0}^{n} \\binom{n}{k} a^{n-k}b^k$$", desc_kr: "두 항의 합의 거듭제곱을 전개하는 공식입니다.", desc_en: "A formula for expanding powers of a binomial expression.", params: { n: { d: 4, min: 1, max: 8, step: 1, kr: "지수 n", en: "Power n" }, a: { d: 1, min: 1, max: 3, step: 1, kr: "항 a", en: "Term a" }, b: { d: 1, min: 1, max: 3, step: 1, kr: "항 b", en: "Term b" }, showPascal: { d: true, kr: "파스칼 삼각형", en: "Pascal's Triangle" } }, real: ["확률 이항분포", "근사 계산", "조합 경우의 수"] },
  { cat: "04_high_math", id: "differential-equations", kr: "미분방정식", en: "Differential Equations", diff: "High-3", conn: ["derivatives", "integrals"], formula: "$$\\frac{dy}{dx} = f(x, y)$$", desc_kr: "미지 함수와 그 도함수 사이의 관계를 나타내는 방정식입니다.", desc_en: "Equations involving a function and its derivatives.", params: { k: { d: 0.5, min: 0.1, max: 2, step: 0.1, kr: "계수 k", en: "Coefficient k" }, y0: { d: 1, min: 0.1, max: 5, step: 0.1, kr: "초기값 y₀", en: "Initial y₀" }, showField: { d: true, kr: "방향장 보기", en: "Show Direction Field" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["인구 성장 모델", "방사성 붕괴", "스프링 진동"] },

  // ── 05_high_physics (15) ──
  { cat: "05_high_physics", id: "projectile-motion", kr: "포물선 운동", en: "Projectile Motion", diff: "High-1", conn: ["gravity", "quadratic-function"], formula: "$$y = v_0 \\sin\\theta \\cdot t - \\frac{1}{2}gt^2$$", desc_kr: "물체를 비스듬히 던졌을 때 포물선을 그리며 이동하는 운동입니다.", desc_en: "The curved path of an object thrown at an angle.", params: { velocity: { d: 20, min: 5, max: 50, step: 1, kr: "초속 (m/s)", en: "Velocity (m/s)" }, angle: { d: 45, min: 5, max: 85, step: 5, kr: "발사각 (°)", en: "Launch Angle (°)" }, showTrail: { d: true, kr: "궤적 보기", en: "Show Trail" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["공 던지기", "분수대 물줄기", "포병 사격 계산"] },
  { cat: "05_high_physics", id: "circular-motion", kr: "원운동", en: "Circular Motion", diff: "High-1", conn: ["force-motion", "unit-circle"], formula: "$$a_c = \\frac{v^2}{r}$$", desc_kr: "물체가 원형 경로를 따라 일정한 속력으로 회전하는 운동입니다.", desc_en: "Motion of an object along a circular path.", params: { radius: { d: 3, min: 1, max: 6, step: 0.5, kr: "반지름 (m)", en: "Radius (m)" }, speed: { d: 2, min: 0.5, max: 5, step: 0.5, kr: "속력 (m/s)", en: "Speed (m/s)" }, showVectors: { d: true, kr: "벡터 표시", en: "Show Vectors" } }, real: ["놀이공원 회전 놀이기구", "인공위성 궤도", "세탁기 탈수"] },
  { cat: "05_high_physics", id: "simple-harmonic-motion", kr: "단진동", en: "Simple Harmonic Motion", diff: "High-2", conn: ["sine-wave", "pendulum"], formula: "$$x(t) = A\\cos(\\omega t + \\phi)$$", desc_kr: "평형점을 중심으로 주기적으로 왕복하는 운동입니다.", desc_en: "Periodic back-and-forth motion around an equilibrium position.", params: { amplitude: { d: 2, min: 0.5, max: 4, step: 0.5, kr: "진폭 (m)", en: "Amplitude (m)" }, omega: { d: 2, min: 0.5, max: 5, step: 0.5, kr: "각진동수 ω", en: "Angular freq ω" }, showGraph: { d: true, kr: "그래프 보기", en: "Show Graph" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["스프링 진동", "음파 생성", "진자 시계"] },
  { cat: "05_high_physics", id: "newtons-laws", kr: "뉴턴의 운동 법칙", en: "Newton's Laws", diff: "High-1", conn: ["force-motion", "momentum"], formula: "$$F = ma, \\; F_{12} = -F_{21}$$", desc_kr: "물체의 운동을 설명하는 세 가지 기본 법칙입니다.", desc_en: "Three fundamental laws describing the motion of objects.", params: { mass: { d: 5, min: 1, max: 20, step: 1, kr: "질량 (kg)", en: "Mass (kg)" }, force: { d: 20, min: 1, max: 50, step: 1, kr: "힘 (N)", en: "Force (N)" }, friction: { d: 0.2, min: 0, max: 1, step: 0.1, kr: "마찰 계수", en: "Friction" }, showFBD: { d: true, kr: "자유물체도", en: "Free Body Diagram" } }, real: ["자동차 브레이크", "스케이트보드", "우주 비행"] },
  { cat: "05_high_physics", id: "momentum", kr: "운동량", en: "Momentum", diff: "High-1", conn: ["newtons-laws", "force-motion"], formula: "$$p = mv, \\; \\Delta p = F\\Delta t$$", desc_kr: "물체의 질량과 속도의 곱으로, 운동의 양을 나타냅니다.", desc_en: "The product of mass and velocity, measuring the quantity of motion.", params: { mass1: { d: 2, min: 0.5, max: 10, step: 0.5, kr: "질량 1 (kg)", en: "Mass 1 (kg)" }, vel1: { d: 5, min: -10, max: 10, step: 1, kr: "속도 1 (m/s)", en: "Velocity 1" }, mass2: { d: 3, min: 0.5, max: 10, step: 0.5, kr: "질량 2 (kg)", en: "Mass 2 (kg)" }, showCollision: { d: true, kr: "충돌 보기", en: "Show Collision" } }, real: ["당구공 충돌", "교통사고 분석", "로켓 추진"] },
  { cat: "05_high_physics", id: "work-energy", kr: "일과 에너지", en: "Work & Energy", diff: "High-1", conn: ["energy-conservation", "force-motion"], formula: "$$W = F \\cdot d \\cdot \\cos\\theta$$", desc_kr: "힘이 물체를 이동시킬 때 한 일의 양입니다.", desc_en: "The energy transferred when a force moves an object.", params: { force: { d: 20, min: 1, max: 50, step: 1, kr: "힘 (N)", en: "Force (N)" }, distance: { d: 5, min: 1, max: 20, step: 1, kr: "거리 (m)", en: "Distance (m)" }, angle: { d: 0, min: 0, max: 90, step: 5, kr: "각도 (°)", en: "Angle (°)" }, showEnergy: { d: true, kr: "에너지 막대", en: "Energy Bar" } }, real: ["물건 밀기", "계단 올라가기", "기중기 작업"] },
  { cat: "05_high_physics", id: "electric-field", kr: "전기장", en: "Electric Field", diff: "High-2", conn: ["electric-circuit", "magnetic-field"], formula: "$$E = \\frac{kQ}{r^2}$$", desc_kr: "전하 주위의 공간에 형성되는 힘의 장입니다.", desc_en: "The field of force surrounding an electric charge.", params: { charge: { d: 5, min: -10, max: 10, step: 1, kr: "전하 (μC)", en: "Charge (μC)" }, showLines: { d: true, kr: "전기력선 보기", en: "Show Field Lines" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["정전기", "번개", "콘덴서"] },
  { cat: "05_high_physics", id: "magnetic-field", kr: "자기장", en: "Magnetic Field", diff: "High-2", conn: ["electric-field", "electromagnetic-induction"], formula: "$$F = qvB\\sin\\theta$$", desc_kr: "자석이나 전류 주위에 형성되는 힘의 장입니다.", desc_en: "The field produced by magnets or moving electric charges.", params: { current: { d: 5, min: 1, max: 20, step: 1, kr: "전류 (A)", en: "Current (A)" }, distance: { d: 3, min: 0.5, max: 10, step: 0.5, kr: "거리 (cm)", en: "Distance (cm)" }, showField: { d: true, kr: "자기력선 보기", en: "Show Field" } }, real: ["나침반", "MRI 장치", "전동기"] },
  { cat: "05_high_physics", id: "electromagnetic-induction", kr: "전자기 유도", en: "Electromagnetic Induction", diff: "High-3", conn: ["magnetic-field"], formula: "$$\\varepsilon = -\\frac{d\\Phi_B}{dt}$$", desc_kr: "자기장의 변화에 의해 전류가 유도되는 현상입니다.", desc_en: "The production of voltage by a changing magnetic field.", params: { turns: { d: 10, min: 1, max: 30, step: 1, kr: "코일 감은 수", en: "Turns" }, speed: { d: 2, min: 0.5, max: 5, step: 0.5, kr: "자석 속도", en: "Magnet Speed" }, showVoltage: { d: true, kr: "전압 표시", en: "Show Voltage" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["발전기", "무선 충전", "교통카드"] },
  { cat: "05_high_physics", id: "wave-interference", kr: "파동의 간섭", en: "Wave Interference", diff: "High-2", conn: ["waves-basic", "sine-wave"], formula: "$$y = y_1 + y_2$$", desc_kr: "두 파동이 만나서 세기가 강해지거나 약해지는 현상입니다.", desc_en: "When two waves overlap, they combine constructively or destructively.", params: { freq1: { d: 2, min: 0.5, max: 5, step: 0.5, kr: "진동수 1", en: "Frequency 1" }, freq2: { d: 2.5, min: 0.5, max: 5, step: 0.5, kr: "진동수 2", en: "Frequency 2" }, showSum: { d: true, kr: "합성파 보기", en: "Show Sum" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["소음 제거 헤드폰", "악기 화음", "영의 이중 슬릿 실험"] },
  { cat: "05_high_physics", id: "doppler-effect", kr: "도플러 효과", en: "Doppler Effect", diff: "High-2", conn: ["waves-basic", "speed-velocity"], formula: "$$f' = f \\cdot \\frac{v \\pm v_o}{v \\mp v_s}$$", desc_kr: "파원과 관측자 사이의 상대 운동에 의해 진동수가 달라지는 현상입니다.", desc_en: "The change in frequency of a wave due to relative motion.", params: { sourceSpeed: { d: 10, min: 0, max: 50, step: 1, kr: "파원 속도", en: "Source Speed" }, frequency: { d: 3, min: 1, max: 8, step: 0.5, kr: "원래 진동수", en: "Original Freq" }, showWaves: { d: true, kr: "파면 보기", en: "Show Wavefronts" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["구급차 사이렌", "우주 적색편이", "속도 측정 레이더"] },
  { cat: "05_high_physics", id: "thermodynamics", kr: "열역학", en: "Thermodynamics", diff: "High-3", conn: ["heat-transfer", "energy-conservation"], formula: "$$\\Delta U = Q - W$$", desc_kr: "열과 일의 상호 변환을 다루는 물리학의 분야입니다.", desc_en: "The study of heat, work, and energy transformations.", params: { Q: { d: 100, min: 0, max: 500, step: 10, kr: "열량 (J)", en: "Heat (J)" }, W: { d: 40, min: 0, max: 300, step: 10, kr: "일 (J)", en: "Work (J)" }, showCycle: { d: true, kr: "사이클 보기", en: "Show Cycle" } }, real: ["자동차 엔진", "냉장고 원리", "발전소"] },
  { cat: "05_high_physics", id: "capacitor", kr: "축전기", en: "Capacitor", diff: "High-2", conn: ["electric-field", "electric-circuit"], formula: "$$C = \\frac{Q}{V}, \\; E = \\frac{1}{2}CV^2$$", desc_kr: "전하를 저장하는 장치로, 두 도체판 사이에 전기장이 형성됩니다.", desc_en: "A device that stores electric charge between two plates.", params: { capacitance: { d: 10, min: 1, max: 50, step: 1, kr: "전기용량 (μF)", en: "Capacitance (μF)" }, voltage: { d: 5, min: 1, max: 20, step: 1, kr: "전압 (V)", en: "Voltage (V)" }, showCharge: { d: true, kr: "충전 보기", en: "Show Charging" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["카메라 플래시", "제세동기", "터치스크린"] },
  { cat: "05_high_physics", id: "ohms-law", kr: "옴의 법칙", en: "Ohm's Law", diff: "High-1", conn: ["electric-circuit"], formula: "$$V = IR$$", desc_kr: "전압, 전류, 저항 사이의 기본적인 관계입니다.", desc_en: "The fundamental relationship between voltage, current, and resistance.", params: { voltage: { d: 12, min: 1, max: 24, step: 1, kr: "전압 (V)", en: "Voltage (V)" }, resistance: { d: 4, min: 1, max: 20, step: 1, kr: "저항 (Ω)", en: "Resistance (Ω)" }, showMeter: { d: true, kr: "계기 보기", en: "Show Meters" } }, real: ["가전제품 소비전력", "퓨즈 용량 계산", "LED 저항 선택"] },
  { cat: "05_high_physics", id: "pendulum", kr: "진자 운동", en: "Pendulum Motion", diff: "High-1", conn: ["simple-harmonic-motion", "gravity"], formula: "$$T = 2\\pi\\sqrt{\\frac{L}{g}}$$", desc_kr: "추가 실에 매달려 좌우로 왕복하는 운동입니다.", desc_en: "The swinging motion of a weight on a string.", params: { length: { d: 2, min: 0.5, max: 5, step: 0.5, kr: "줄 길이 (m)", en: "Length (m)" }, angle0: { d: 30, min: 5, max: 60, step: 5, kr: "초기 각도 (°)", en: "Initial Angle (°)" }, showTrail: { d: true, kr: "궤적 보기", en: "Show Trail" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["진자 시계", "그네", "메트로놈"] },

  // ── 06_data_structures (15) ──
  { cat: "06_data_structures", id: "array", kr: "배열", en: "Array", diff: "High-1", conn: ["linked-list", "binary-search"], formula: "", desc_kr: "같은 타입의 데이터를 연속된 메모리 공간에 저장하는 자료구조입니다.", desc_en: "A contiguous block of memory storing elements of the same type.", params: { size: { d: 8, min: 3, max: 15, step: 1, kr: "배열 크기", en: "Array Size" }, highlightIndex: { d: 3, min: 0, max: 14, step: 1, kr: "인덱스 선택", en: "Select Index" }, showAddress: { d: true, kr: "주소 보기", en: "Show Address" } }, real: ["이미지 픽셀 저장", "학생 성적표", "게임 인벤토리"], extra: "접근 O(1), 삽입/삭제 O(n)" },
  { cat: "06_data_structures", id: "linked-list", kr: "연결 리스트", en: "Linked List", diff: "High-1", conn: ["array", "stack", "queue"], formula: "", desc_kr: "각 노드가 데이터와 다음 노드의 포인터를 가진 자료구조입니다.", desc_en: "A sequence of nodes where each node points to the next.", params: { nodes: { d: 5, min: 2, max: 10, step: 1, kr: "노드 수", en: "Nodes" }, insertPos: { d: 2, min: 0, max: 9, step: 1, kr: "삽입 위치", en: "Insert Position" }, showPointers: { d: true, kr: "포인터 보기", en: "Show Pointers" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["음악 재생목록", "브라우저 방문 기록", "다항식 표현"], extra: "삽입/삭제 O(1), 접근 O(n)" },
  { cat: "06_data_structures", id: "stack", kr: "스택", en: "Stack", diff: "High-1", conn: ["linked-list", "recursion"], formula: "", desc_kr: "후입선출(LIFO) 원칙을 따르는 자료구조입니다.", desc_en: "A Last-In-First-Out (LIFO) data structure.", params: { maxSize: { d: 6, min: 3, max: 10, step: 1, kr: "최대 크기", en: "Max Size" }, pushValue: { d: 42, min: 0, max: 99, step: 1, kr: "Push 값", en: "Push Value" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["실행 취소(Undo)", "괄호 짝 맞추기", "함수 호출 스택"], extra: "Push/Pop O(1)" },
  { cat: "06_data_structures", id: "queue", kr: "큐", en: "Queue", diff: "High-1", conn: ["linked-list", "bfs-dfs"], formula: "", desc_kr: "선입선출(FIFO) 원칙을 따르는 자료구조입니다.", desc_en: "A First-In-First-Out (FIFO) data structure.", params: { maxSize: { d: 6, min: 3, max: 10, step: 1, kr: "최대 크기", en: "Max Size" }, enqueueValue: { d: 7, min: 0, max: 99, step: 1, kr: "Enqueue 값", en: "Enqueue Value" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["프린터 대기열", "콜센터 대기", "BFS 탐색"], extra: "Enqueue/Dequeue O(1)" },
  { cat: "06_data_structures", id: "binary-tree", kr: "이진 트리", en: "Binary Tree", diff: "High-2", conn: ["binary-search-tree", "heap"], formula: "", desc_kr: "각 노드가 최대 두 개의 자식 노드를 가지는 트리 자료구조입니다.", desc_en: "A tree where each node has at most two children.", params: { depth: { d: 3, min: 2, max: 5, step: 1, kr: "깊이", en: "Depth" }, showValues: { d: true, kr: "값 표시", en: "Show Values" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["파일 시스템", "조직도", "의사 결정 트리"], extra: "높이 h일 때 최대 노드 수: 2^(h+1) - 1" },
  { cat: "06_data_structures", id: "binary-search-tree", kr: "이진 탐색 트리", en: "Binary Search Tree", diff: "High-2", conn: ["binary-tree", "binary-search"], formula: "", desc_kr: "왼쪽 자식은 부모보다 작고, 오른쪽 자식은 부모보다 큰 이진 트리입니다.", desc_en: "A binary tree where left < parent < right for all nodes.", params: { nodeCount: { d: 7, min: 3, max: 12, step: 1, kr: "노드 수", en: "Nodes" }, searchValue: { d: 5, min: 1, max: 20, step: 1, kr: "탐색 값", en: "Search Value" }, showPath: { d: true, kr: "경로 보기", en: "Show Path" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["사전 검색", "데이터베이스 인덱스", "자동 완성"], extra: "평균 탐색 O(log n), 최악 O(n)" },
  { cat: "06_data_structures", id: "heap", kr: "힙", en: "Heap", diff: "High-2", conn: ["binary-tree", "sorting-quick"], formula: "", desc_kr: "부모 노드가 항상 자식 노드보다 크거나(최대힙) 작은(최소힙) 완전 이진 트리입니다.", desc_en: "A complete binary tree where parent >= children (max-heap) or parent <= children (min-heap).", params: { size: { d: 7, min: 3, max: 12, step: 1, kr: "크기", en: "Size" }, isMaxHeap: { d: true, kr: "최대 힙", en: "Max Heap" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["우선순위 큐", "운영체제 작업 스케줄링", "다익스트라 알고리즘"], extra: "삽입/삭제 O(log n), 최대/최소 접근 O(1)" },
  { cat: "06_data_structures", id: "hash-table", kr: "해시 테이블", en: "Hash Table", diff: "High-2", conn: ["array"], formula: "", desc_kr: "키(key)를 해시 함수로 변환하여 값(value)을 빠르게 찾는 자료구조입니다.", desc_en: "A data structure that maps keys to values using a hash function.", params: { tableSize: { d: 8, min: 4, max: 16, step: 1, kr: "테이블 크기", en: "Table Size" }, key: { d: 42, min: 0, max: 99, step: 1, kr: "키", en: "Key" }, showCollision: { d: true, kr: "충돌 보기", en: "Show Collision" } }, real: ["전화번호부", "웹 캐시", "데이터베이스 인덱싱"], extra: "평균 접근 O(1), 최악 O(n)" },
  { cat: "06_data_structures", id: "graph-traversal", kr: "그래프 탐색", en: "Graph Traversal", diff: "High-3", conn: ["bfs-dfs", "queue", "stack"], formula: "", desc_kr: "그래프의 모든 정점을 체계적으로 방문하는 방법입니다.", desc_en: "Systematically visiting all vertices in a graph.", params: { nodes: { d: 7, min: 4, max: 12, step: 1, kr: "정점 수", en: "Nodes" }, edges: { d: 10, min: 4, max: 20, step: 1, kr: "간선 수", en: "Edges" }, showVisited: { d: true, kr: "방문 표시", en: "Show Visited" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["소셜 네트워크 분석", "지도 내비게이션", "웹 크롤링"], extra: "BFS: O(V+E), DFS: O(V+E)" },
  { cat: "06_data_structures", id: "sorting-bubble", kr: "버블 정렬", en: "Bubble Sort", diff: "High-1", conn: ["sorting-quick", "sorting-merge", "array"], formula: "", desc_kr: "인접한 두 원소를 비교하여 교환하며 정렬하는 알고리즘입니다.", desc_en: "Sort by repeatedly swapping adjacent elements that are out of order.", params: { size: { d: 8, min: 4, max: 15, step: 1, kr: "배열 크기", en: "Array Size" }, speed: { d: 1, min: 0.5, max: 3, step: 0.5, kr: "속도", en: "Speed" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["간단한 정렬이 필요한 소규모 데이터", "교육용 정렬 시각화"], extra: "시간 복잡도: O(n²)" },
  { cat: "06_data_structures", id: "sorting-quick", kr: "퀵 정렬", en: "Quick Sort", diff: "High-2", conn: ["sorting-bubble", "sorting-merge", "recursion"], formula: "", desc_kr: "피벗을 기준으로 작은 값과 큰 값을 분할하여 정렬하는 알고리즘입니다.", desc_en: "Divide and conquer sorting using a pivot element.", params: { size: { d: 10, min: 4, max: 15, step: 1, kr: "배열 크기", en: "Array Size" }, speed: { d: 1, min: 0.5, max: 3, step: 0.5, kr: "속도", en: "Speed" }, showPivot: { d: true, kr: "피벗 표시", en: "Show Pivot" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["프로그래밍 언어 내장 정렬", "대규모 데이터 정렬"], extra: "평균 O(n log n), 최악 O(n²)" },
  { cat: "06_data_structures", id: "sorting-merge", kr: "병합 정렬", en: "Merge Sort", diff: "High-2", conn: ["sorting-quick", "recursion"], formula: "", desc_kr: "배열을 반으로 나누고, 정렬한 후 합치는 분할 정복 알고리즘입니다.", desc_en: "Divide the array, sort halves, and merge them back.", params: { size: { d: 8, min: 4, max: 15, step: 1, kr: "배열 크기", en: "Array Size" }, speed: { d: 1, min: 0.5, max: 3, step: 0.5, kr: "속도", en: "Speed" }, showSplit: { d: true, kr: "분할 보기", en: "Show Split" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["외부 정렬", "안정 정렬이 필요한 경우"], extra: "항상 O(n log n), 공간 O(n)" },
  { cat: "06_data_structures", id: "binary-search", kr: "이진 탐색", en: "Binary Search", diff: "High-1", conn: ["array", "binary-search-tree"], formula: "", desc_kr: "정렬된 배열에서 반씩 줄여가며 원하는 값을 찾는 알고리즘입니다.", desc_en: "Efficiently find a value in a sorted array by halving the search space.", params: { size: { d: 15, min: 5, max: 20, step: 1, kr: "배열 크기", en: "Array Size" }, target: { d: 7, min: 1, max: 20, step: 1, kr: "탐색 값", en: "Target" }, showRange: { d: true, kr: "범위 보기", en: "Show Range" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["사전에서 단어 찾기", "도서관 책 분류 검색", "게임 랭킹 검색"], extra: "시간 복잡도: O(log n)" },
  { cat: "06_data_structures", id: "recursion", kr: "재귀", en: "Recursion", diff: "High-2", conn: ["stack", "binary-tree"], formula: "", desc_kr: "함수가 자기 자신을 호출하여 문제를 해결하는 기법입니다.", desc_en: "A technique where a function calls itself to solve subproblems.", params: { n: { d: 5, min: 1, max: 10, step: 1, kr: "입력 n", en: "Input n" }, showStack: { d: true, kr: "호출 스택 보기", en: "Show Call Stack" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["팩토리얼 계산", "피보나치 수열", "폴더 탐색"], extra: "기저 조건(base case)이 반드시 필요" },
  { cat: "06_data_structures", id: "big-o-notation", kr: "빅오 표기법", en: "Big-O Notation", diff: "High-1", conn: ["sorting-bubble", "sorting-quick", "binary-search"], formula: "", desc_kr: "알고리즘의 시간 복잡도를 나타내는 표기법입니다.", desc_en: "A notation describing the upper bound of an algorithm's time complexity.", params: { inputSize: { d: 20, min: 5, max: 50, step: 5, kr: "입력 크기 n", en: "Input Size n" }, showAll: { d: true, kr: "모든 복잡도", en: "Show All" }, animate: { d: true, kr: "애니메이션", en: "Animate" } }, real: ["알고리즘 성능 비교", "시스템 설계 시 선택 기준", "면접 준비"], extra: "O(1) < O(log n) < O(n) < O(n log n) < O(n²)" },
];

function buildMd(c) {
  const connStr = c.conn.map(x => `"${x}"`).join(", ");
  const paramLines = Object.entries(c.params).map(([k, v]) => {
    if (typeof v.d === "boolean") {
      return `  ${k}: { default: ${v.d}, label: { kr: "${v.kr}", en: "${v.en}" } }`;
    }
    return `  ${k}: { default: ${v.d}, min: ${v.min}, max: ${v.max}, step: ${v.step}, label: { kr: "${v.kr}", en: "${v.en}" } }`;
  }).join("\n");

  const realList = c.real.map(r => `- **${r}**`).join("\n");
  const extraSection = c.extra ? `\n## 핵심 정리\n\n> ${c.extra}\n` : "";
  const connLinks = c.conn.map(x => `- [[${x}]]`).join("\n");

  return `---
id: "${c.id}"
title: { kr: "${c.kr}", en: "${c.en}" }
difficulty: "${c.diff}"
connections: [${connStr}]
---

# ${c.kr} / ${c.en}

${c.desc_kr}

${c.desc_en}
${c.formula ? `\n${c.formula}\n` : ""}
\`\`\`math-anim
type: ${c.id}
params:
${paramLines}
\`\`\`

## 실생활 활용

${realList}
${extraSection}
## 관련 개념

${connLinks}
`;
}

let count = 0;
for (const c of concepts) {
  const dir = join(LIB, c.cat);
  mkdirSync(dir, { recursive: true });
  const filePath = join(dir, `${c.id}.md`);
  writeFileSync(filePath, buildMd(c), "utf-8");
  count++;
}

console.log(`Generated ${count} concept files.`);
